'use client';

import { forwardRef, ReactNode } from 'react';
import { BaseAbilityId } from '@/types';
import { DiagnosisDocument } from '@/lib/diagnosis/document';

const abilityLabels: Record<BaseAbilityId,string> = {field:'現場行動力',spending:'積み耐性',evangelism:'布教力',analysis:'解釈力',community:'同担連帯力',recognition:'認知欲',afterglow:'余韻持続力',archive:'記録保存力'};
const abilityKeys = Object.keys(abilityLabels) as BaseAbilityId[];
const palette = ['#7c5ac7','#d85e9f','#6580cf','#a86bbd'];

function Lines({text,x,y,size=28,max=22,line=1.35,anchor='start',weight=400}:{text:string;x:number;y:number;size?:number;max?:number;line?:number;anchor?:'start'|'middle';weight?:number}) {
  const rows=[] as string[];
  for(let i=0;i<text.length;i+=max) rows.push(text.slice(i,i+max));
  return <text x={x} y={y} fontSize={size} fill="#473d69" textAnchor={anchor} fontWeight={weight}>{rows.map((row,i)=><tspan x={x} dy={i?size*line:0} key={`${row}-${i}`}>{row}</tspan>)}</text>;
}

function Decorations({width,height}:{width:number;height:number}) {
  return <g opacity=".9"><path d={`M35 120 Q110 50 180 105`} fill="none" stroke="#eec4db" strokeWidth="4"/><text x={42} y={72} fontSize="34" fill="#d7a44a">✦</text><text x={width-105} y={95} fontSize="42" fill="#d985b6">♡</text><text x={width-78} y={height-70} fontSize="34" fill="#8c74cf">✧</text><circle cx={width-52} cy={180} r="16" fill="#f5d9e9"/><circle cx="55" cy={height-135} r="12" fill="#dcd3f5"/></g>;
}

function Character({code,x,y,size}:{code:string;x:number;y:number;size:number}) {
  const color=palette[code.charCodeAt(0)%palette.length];
  return <g transform={`translate(${x} ${y})`}><circle cx={size/2} cy={size/2} r={size/2} fill="#fff" stroke="#d8c9ef" strokeWidth="5"/><path d={`M${size*.25} ${size*.72} Q${size*.5} ${size*.5} ${size*.75} ${size*.72} L${size*.82} ${size*.95} L${size*.18} ${size*.95}Z`} fill={color} opacity=".82"/><circle cx={size*.5} cy={size*.39} r={size*.22} fill="#ffe7dc"/><path d={`M${size*.28} ${size*.38} Q${size*.32} ${size*.08} ${size*.52} ${size*.12} Q${size*.78} ${size*.14} ${size*.72} ${size*.46} Q${size*.63} ${size*.25} ${size*.28} ${size*.38}`} fill={color}/><circle cx={size*.43} cy={size*.4} r={size*.018} fill="#58466f"/><circle cx={size*.57} cy={size*.4} r={size*.018} fill="#58466f"/><path d={`M${size*.45} ${size*.49} Q${size*.5} ${size*.53} ${size*.56} ${size*.49}`} fill="none" stroke="#bb6e89" strokeWidth="3"/><text x={size*.5} y={size*.87} textAnchor="middle" fontSize={size*.09} fontWeight="800" fill="#fff">{code}</text><text x={size*.82} y={size*.22} fontSize={size*.15} fill="#d7a44a">✦</text></g>;
}

function RadarGraphic({document,cx,cy,r}:{document:DiagnosisDocument;cx:number;cy:number;r:number}) {
  const point=(i:number,value:number)=>{const a=-Math.PI/2+i*Math.PI*2/8;return `${cx+Math.cos(a)*r*value/100},${cy+Math.sin(a)*r*value/100}`};
  const ring=(value:number)=>abilityKeys.map((_,i)=>point(i,value)).join(' ');
  return <g>{[25,50,75,100].map(v=><polygon key={v} points={ring(v)} fill={v===100?'#fbf8ff':'none'} stroke="#d7caea" strokeWidth="2"/>)}{abilityKeys.map((key,i)=>{const a=-Math.PI/2+i*Math.PI*2/8;return <g key={key}><line x1={cx} y1={cy} x2={cx+Math.cos(a)*r} y2={cy+Math.sin(a)*r} stroke="#ded3ee"/><text x={cx+Math.cos(a)*(r+38)} y={cy+Math.sin(a)*(r+28)} fontSize="18" textAnchor="middle" fill="#66557f">{abilityLabels[key]}</text></g>})}<polygon points={abilityKeys.map((key,i)=>point(i,document.abilities[key])).join(' ')} fill="#c278d555" stroke="#8b5cc7" strokeWidth="5"/></g>;
}

function Frame({width,height,children,label}:{width:number;height:number;children:ReactNode;label:string}) {return <><rect width={width} height={height} fill="#f6f0ff"/><rect x="24" y="24" width={width-48} height={height-48} rx="38" fill="#fffafeee" stroke="#cbb9e5" strokeWidth="4"/><Decorations width={width} height={height}/><g><rect x="58" y="52" width="265" height="54" rx="27" fill="#7658b8"/><text x="190" y="88" textAnchor="middle" fontSize="25" fontWeight="800" fill="#fff">OSHICOA 16</text><text x={width-60} y="86" textAnchor="end" fontSize="21" fontWeight="700" fill="#a586c8">{label}</text></g>{children}</>}

export const DiagnosisSheet = forwardRef<SVGSVGElement,{document:DiagnosisDocument;className?:string}>(({document,className},ref)=>{const {type}=document;return <svg ref={ref} className={className} viewBox="0 0 1080 1620" role="img" aria-label={`${type.name}のヲタク生態診断書`} xmlns="http://www.w3.org/2000/svg"><Frame width={1080} height={1620} label="OTAKU ECOLOGY SHEET"><Character code={type.code} x={390} y={125} size={300}/><text x="540" y="480" textAnchor="middle" fontSize="70" fontWeight="900" fill="#342858">{type.name}</text><text x="540" y="530" textAnchor="middle" fontSize="27" fontWeight="800" fill="#9a79c1">{type.code}　生態レア度 {'★'.repeat(document.rarity)}{'☆'.repeat(5-document.rarity)}</text><Lines text={type.catchphrase} x={540} y={590} size={31} max={28} anchor="middle" weight={700}/><g transform="translate(62 660)"><rect width="575" height="430" rx="28" fill="#ffffffcc" stroke="#dacded" strokeWidth="3"/><text x="30" y="52" fontSize="27" fontWeight="800" fill="#7b5aaa">生態プロフィール</text>{[['生息地',type.habitat],['主食',type.mainFood],['口癖',type.habitPhrase],['特殊能力',type.specialAbility],['弱点',type.weakness]].map(([label,value],i)=><g key={label} transform={`translate(30 ${88+i*68})`}><text fontSize="20" fontWeight="800" fill="#c45f95">{label}</text><Lines text={value} x={112} y={0} size={19} max={31}/></g>)}</g><RadarGraphic document={document} cx={850} cy={855} r={145}/><g transform="translate(62 1125)"><rect width="956" height="370" rx="28" fill="#fff" stroke="#dacded" strokeWidth="3"/><text x="30" y="52" fontSize="27" fontWeight="800" fill="#7b5aaa">あなたの業</text>{document.karmaTags.map((tag,i)=><g key={tag} transform={`translate(${30+i*300} 72)`}><rect width="280" height="50" rx="25" fill="#f3d9e9"/><text x="140" y="34" textAnchor="middle" fontSize="19" fontWeight="800" fill="#985078">#{tag}</text></g>)}<text x="30" y="176" fontSize="25" fontWeight="800" fill="#7b5aaa">限界になると</text><Lines text={type.extremeBehavior} x={30} y={220} size={23} max={48}/><text x="30" y="310" fontSize="18" fill="#9a8aaf">保存して、推し友にもあなたの生態を晒そう。</text></g></Frame></svg>});
DiagnosisSheet.displayName='DiagnosisSheet';

export const SquareShareCard = forwardRef<SVGSVGElement,{document:DiagnosisDocument;className?:string}>(({document,className},ref)=>{const {type}=document;return <svg ref={ref} className={className} viewBox="0 0 1200 1200" role="img" aria-label={`${type.name}のX共有カード`} xmlns="http://www.w3.org/2000/svg"><Frame width={1200} height={1200} label="MY OTAKU TYPE"><Character code={type.code} x={430} y={130} size={340}/><text x="600" y="560" textAnchor="middle" fontSize="82" fontWeight="900" fill="#342858">{type.name}</text><text x="600" y="615" textAnchor="middle" fontSize="29" fontWeight="800" fill="#9877be">{type.code}　生態レア度 {'★'.repeat(document.rarity)}{'☆'.repeat(5-document.rarity)}</text><Lines text={type.catchphrase} x={600} y={685} size={34} max={28} anchor="middle" weight={700}/><RadarGraphic document={document} cx={325} cy={920} r={150}/><g transform="translate(600 800)"><text fontSize="27" fontWeight="800" fill="#7b5aaa">あなたの業</text>{document.karmaTags.map((tag,i)=><g key={tag} transform={`translate(0 ${35+i*66})`}><rect width="480" height="52" rx="26" fill="#f3d9e9"/><text x="240" y="35" textAnchor="middle" fontSize="21" fontWeight="800" fill="#985078">#{tag}</text></g>)}</g><text x="1100" y="1140" textAnchor="end" fontSize="23" fontWeight="800" fill="#8b70b3">#OSHICOA16</text></Frame></svg>});
SquareShareCard.displayName='SquareShareCard';

export const StoryShareCard = forwardRef<SVGSVGElement,{document:DiagnosisDocument;className?:string}>(({document,className},ref)=>{const {type}=document;return <svg ref={ref} className={className} viewBox="0 0 1080 1920" role="img" aria-label={`${type.name}のストーリー共有カード`} xmlns="http://www.w3.org/2000/svg"><Frame width={1080} height={1920} label="STORY CARD"><text x="540" y="165" textAnchor="middle" fontSize="25" fill="#9277b4">私のヲタク生態は</text><Character code={type.code} x={310} y={210} size={460}/><text x="540" y="760" textAnchor="middle" fontSize="76" fontWeight="900" fill="#342858">{type.name}</text><text x="540" y="818" textAnchor="middle" fontSize="29" fontWeight="800" fill="#9877be">{type.code}　生態レア度 {'★'.repeat(document.rarity)}{'☆'.repeat(5-document.rarity)}</text><Lines text={type.catchphrase} x={540} y={900} size={34} max={27} anchor="middle" weight={700}/><g transform="translate(90 1000)"><rect width="900" height="320" rx="30" fill="#fff" stroke="#d7cae9" strokeWidth="3"/><text x="35" y="58" fontSize="29" fontWeight="800" fill="#7b5aaa">生態プロフィール</text><text x="35" y="120" fontSize="21" fontWeight="800" fill="#c45f95">生息地</text><Lines text={type.habitat} x={155} y={120} size={21} max={32}/><text x="35" y="205" fontSize="21" fontWeight="800" fill="#c45f95">特殊能力</text><Lines text={type.specialAbility} x={155} y={205} size={21} max={32}/></g><RadarGraphic document={document} cx={330} cy={1560} r={170}/><g transform="translate(610 1400)"><text fontSize="29" fontWeight="800" fill="#7b5aaa">あなたの業</text>{document.karmaTags.map((tag,i)=><g key={tag} transform={`translate(0 ${38+i*72})`}><rect width="370" height="56" rx="28" fill="#f3d9e9"/><text x="185" y="38" textAnchor="middle" fontSize="21" fontWeight="800" fill="#985078">#{tag}</text></g>)}</g><text x="540" y="1840" textAnchor="middle" fontSize="24" fontWeight="800" fill="#8b70b3">あなたも診断してみてね　#OSHICOA16</text></Frame></svg>});
StoryShareCard.displayName='StoryShareCard';

export {abilityKeys,abilityLabels};
